name: npkg Package

on:
  push:
    branches:
      - main
jobs:
   build-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        env:
           NODE_AUTH_TOKEN: ${{secrets.TP_NPM_TOKEN}}
        with:
          node-version: 16.13.x
          registry-url: https://registry.npmjs.org/
      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build
          npm run build:npkg-tinymce-plugin
      - name: publish-npm
        run: |
          cd dist
          npm publish --scope=@npkg --access public